<a href="https://colab.research.google.com/github/mmartigani/MachineLearning2/blob/main/ML5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

In [1]:
datos ={"nombre":["pedro", "juan","lorena"],
        "edad":[25,39,33]}
datos

{'nombre': ['pedro', 'juan', 'lorena'], 'edad': [25, 39, 33]}

In [4]:
df = pd.DataFrame(datos)
df

   nombre  edad
0   pedro    25
1    juan    39
2  lorena    33

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df["nombre"]

0     pedro
1      juan
2    lorena
Name: nombre, dtype: object

In [7]:
df["edad"]

0    25
1    39
2    33
Name: edad, dtype: int64

In [8]:
df.nombre

0     pedro
1      juan
2    lorena
Name: nombre, dtype: object

In [3]:
import pandas as pd

In [11]:
df = pd.read_csv("/content/Precipitaciones.csv")
df.head(5)

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7

In [9]:
df.head(2)

  nombre  edad
0  pedro    25
1   juan    39

In [10]:
df.tail(2)

   nombre  edad
1    juan    39
2  lorena    33

In [12]:
df.shape

(52, 14)

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.columns

Index(['region', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre',
       'anual'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      52 non-null     object
 1   enero       52 non-null     float64
 2   febrero     52 non-null     float64
 3   marzo       52 non-null     float64
 4   abril       52 non-null     float64
 5   mayo        52 non-null     float64
 6   junio       52 non-null     float64
 7   julio       52 non-null     float64
 8   agosto      52 non-null     float64
 9   septiembre  52 non-null     float64
 10  octubre     52 non-null     float64
 11  noviembre   52 non-null     float64
 12  diciembre   52 non-null     float64
 13  anual       52 non-null     float64
dtypes: float64(13), object(1)
memory usage: 5.8+ KB

In [16]:
df.describe()

,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,92.996154,78.632692,26.684615,64.500000,38.305769,54.182692,11.840385,17.178846,62.246154,54.373077,82.494231,76.192308,659.626923
std,57.127171,67.454280,31.473913,21.421942,29.079576,36.821635,13.256390,13.939496,28.581205,36.619785,91.689789,80.409042,352.905548
min,26.800000,2.300000,3.300000,3.500000,0.700000,1.100000,0.000000,0.000000,0.900000,1.000000,7.100000,1.800000,108.200000
25%,53.825000,32.825000,9.125000,53.950000,18.875000,26.325000,1.600000,4.850000,46.000000,29.825000,32.375000,22.075000,455.925000
50%,73.950000,62.600000,17.200000,62.700000,35.650000,50.400000,6.150000,16.500000,62.300000,46.550000,46.950000,47.950000,548.550000
75%,97.300000,102.550000,35.425000,77.625000,48.750000,78.025000,17.875000,26.550000,81.625000,74.500000,102.725000,107.000000,665.150000
max,261.900000,335.700000,209.800000,128.400000,149.500000,145.000000,46.800000,57.000000,122.800000,175.700000,384.600000,314.700000,1575.400000

In [17]:
serie =df["region"]
serie.head()

0    A CORUNA
1    ALBACETE
2    ALICANTE
3     ALMERIA
4       ARABA
Name: region, dtype: object

In [18]:
datos = [10,20,30,40,50]
serie2=pd.Series(datos)
serie2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [20]:
serie2[0]=serie2[0]+10
serie2

0    30
1    30
2    40
3    50
4    60
dtype: int64

In [19]:
serie2 = serie2 +10
serie2

0    20
1    30
2    40
3    50
4    60
dtype: int64

In [21]:
serie2 = serie2 *2
serie2

0     60
1     60
2     80
3    100
4    120
dtype: int64

In [22]:
indices = ["a", "b", "c", "d", "e"]
serie3=pd.Series(datos,indices)
serie3

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [23]:
capitales={"argentina":"buenos aires", "peru":"lima","españa":"madrid"}
serie4=pd.Series(capitales)
serie4

argentina    buenos aires
peru                 lima
españa             madrid
dtype: object

In [24]:
data1={"id_producto":[1001,1002,1003,1003],
       "cantidad_vendida":[30, None,25,25],
       "precio":[20.5,15.0,None,22.5]}
data1

{'id_producto': [1001, 1002, 1003, 1003],
 'cantidad_vendida': [30, None, 25, 25],
 'precio': [20.5, 15.0, None, 22.5]}

In [25]:
df1=pd.DataFrame(data1)
df1

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [27]:
#vemos datos nulos
#los True son los datos nulos
df1.isnull()

   id_producto  cantidad_vendida  precio
0        False             False   False
1        False              True   False
2        False             False    True
3        False             False   False

In [28]:
df1.isnull().sum()

id_producto         0
cantidad_vendida    1
precio              1
dtype: int64

In [29]:
df_eliminados = df1.dropna()
df_eliminados

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
3         1003              25.0    22.5

In [31]:
valores_nuevos={"cantidad_vendida":0,"precio":df1["precio"].mean()}
valores_rellenados = df1.fillna(valores_nuevos)
valores_rellenados

   id_producto  cantidad_vendida     precio
0         1001              30.0  20.500000
1         1002               0.0  15.000000
2         1003              25.0  19.333333
3         1003              25.0  22.500000

In [32]:
valores_rellenados["cantidad_vendida"]=valores_rellenados["cantidad_vendida"].astype(int)
valores_rellenados

   id_producto  cantidad_vendida     precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333
3         1003                25  22.500000

In [33]:
valores_unicos = valores_rellenados.drop_duplicates(subset="id_producto")
valores_unicos

   id_producto  cantidad_vendida     precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333

In [34]:
s=pd.Series([5,10,15,20,25])
s

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [36]:
filtro= s > 15
s_filtrada = s[filtro]
s_filtrada

3    20
4    25
dtype: int64

In [37]:
s2= pd.Series(["banana", "pera", "melon", "manzana"])
s2

0     banana
1       pera
2      melon
3    manzana
dtype: object

In [38]:
type(s2[0])

str

In [39]:
help(s2.str)

Help on StringMethods in module pandas.core.strings.accessor object:

class StringMethods(pandas.core.base.NoNewAttributesMixin)
 |  StringMethods(data) -> 'None'
 |
 |  Vectorized string functions for Series and Index.
 |
 |  NAs stay NA unless handled otherwise by a particular method.
 |  Patterned after Python's string methods, with some inspiration from
 |  R's stringr package.
 |
 |  Examples
 |  --------
 |  >>> s = pd.Series(["A_Str_Series"])
 |  >>> s
 |  0    A_Str_Series
 |  dtype: object
 |
 |  >>> s.str.split("_")
 |  0    [A, Str, Series]
 |  dtype: object
 |
 |  >>> s.str.replace("_", "")
 |  0    AStrSeries
 |  dtype: object
 |
 |  Method resolution order:
 |      StringMethods
 |      pandas.core.base.NoNewAttributesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __getitem__(self, key)
 |
 |  __init__(self, data) -> 'None'
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  capitalize(self)
 |      Convert strings in the Series/Index to be capitalized.
 |
 |      Equivalent to :meth:`str.capitalize`.
 |
 |      Returns
 |      -------
 |      Series or Index of object
 |
 |      See Also
 |      --------
 |      Series.str.lower : Converts all characters to lowercase.
 |      Series.str.upper : Converts all characters to uppercase.
 |      Series.str.title : Converts first character of each word to uppercase and
 |          remaining to lowercase.
 |      Series.str.capitalize : Converts first character to uppercase and
 |          remaining to lowercase.
 |      Series.str.swapcase : Converts uppercase to lowercase and lowercase to
 |          uppercase.
 |      Series.str.casefold: Removes all case distinctions in the string.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['lower', 'CAPITALS', 'this is a sentence', 'SwApCaSe'])
 |      >>> s
 |      0                 lower
 |      1              CAPITALS
 |      2    this is a sentence
 |      3              SwApCaSe
 |      dtype: object
 |
 |      >>> s.str.lower()
 |      0                 lower
 |      1              capitals
 |      2    this is a sentence
 |      3              swapcase
 |      dtype: object
 |
 |      >>> s.str.upper()
 |      0                 LOWER
 |      1              CAPITALS
 |      2    THIS IS A SENTENCE
 |      3              SWAPCASE
 |      dtype: object
 |
 |      >>> s.str.title()
 |      0                 Lower
 |      1              Capitals
 |      2    This Is A Sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.capitalize()
 |      0                 Lower
 |      1              Capitals
 |      2    This is a sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.swapcase()
 |      0                 LOWER
 |      1              capitals
 |      2    THIS IS A SENTENCE
 |      3              sWaPcAsE
 |      dtype: object
 |
 |  casefold(self)
 |      Convert strings in the Series/Index to be casefolded.
 |
 |      Equivalent to :meth:`str.casefold`.
 |
 |      Returns
 |      -------
 |      Series or Index of object
 |
 |      See Also
 |      --------
 |      Series.str.lower : Converts all characters to lowercase.
 |      Series.str.upper : Converts all characters to uppercase.
 |      Series.str.title : Converts first character of each word to uppercase and
 |          remaining to lowercase.
 |      Series.str.capitalize : Converts first character to uppercase and
 |          remaining to lowercase.
 |      Series.str.swapcase : Converts uppercase to lowercase and lowercase to
 |          uppercase.
 |      Series.str.casefold: Removes all case distinctions in the string.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['lower', 'CAPITALS', 'this is a sentence', 'SwApCaSe'])
 |      >>> s
 |      0                 lower
 |      1              CAPITALS
 |      2    this is a sentence
 |      3              SwApCaSe
 |      dtype: object
 |
 |      >>> s.str.lower()
 |      0                 lower
 |      1              capitals
 |      2    this is a sentence
 |      3              swapcase
 |      dtype: object
 |
 |      >>> s.str.upper()
 |      0                 LOWER
 |      1              CAPITALS
 |      2    THIS IS A SENTENCE
 |      3              SWAPCASE
 |      dtype: object
 |
 |      >>> s.str.title()
 |      0                 Lower
 |      1              Capitals
 |      2    This Is A Sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.capitalize()
 |      0                 Lower
 |      1              Capitals
 |      2    This is a sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.swapcase()
 |      0                 LOWER
 |      1              capitals
 |      2    THIS IS A SENTENCE
 |      3              sWaPcAsE
 |      dtype: object
 |
 |  cat(self, others=None, sep=None, na_rep=None, join: 'AlignJoin' = 'left') -> 'str | Series | Index'
 |      Concatenate strings in the Series/Index with given separator.
 |
 |      If `others` is specified, this function concatenates the Series/Index
 |      and elements of `others` element-wise.
 |      If `others` is not passed, then all values in the Series/Index are
 |      concatenated into a single string with a given `sep`.
 |
 |      Parameters
 |      ----------
 |      others : Series, Index, DataFrame, np.ndarray or list-like
 |          Series, Index, DataFrame, np.ndarray (one- or two-dimensional) and
 |          other list-likes of strings must have the same length as the
 |          calling Series/Index, with the exception of indexed objects (i.e.
 |          Series/Index/DataFrame) if `join` is not None.
 |
 |          If others is a list-like that contains a combination of Series,
 |          Index or np.ndarray (1-dim), then all elements will be unpacked and
 |          must satisfy the above criteria individually.
 |
 |          If others is None, the method returns the concatenation of all
 |          strings in the calling Series/Index.
 |      sep : str, default ''
 |          The separator between the different elements/columns. By default
 |          the empty string `''` is used.
 |      na_rep : str or None, default None
 |          Representation that is inserted for all missing values:
 |
 |          - If `na_rep` is None, and `others` is None, missing values in the
 |            Series/Index are omitted from the result.
 |          - If `na_rep` is None, and `others` is not None, a row containing a
 |            missing value in any of the columns (before concatenation) will
 |            have a missing value in the result.
 |      join : {'left', 'right', 'outer', 'inner'}, default 'left'
 |          Determines the join-style between the calling Series/Index and any
 |          Series/Index/DataFrame in `others` (objects without an index need
 |          to match the length of the calling Series/Index). To disable
 |          alignment, use `.values` on any Series/Index/DataFrame in `others`.
 |
 |      Returns
 |      -------
 |      str, Series or Index
 |          If `others` is None, `str` is returned, otherwise a `Series/Index`
 |          (same type as caller) of objects is returned.
 |
 |      See Also
 |      --------
 |      split : Split each string in the Series/Index.
 |      join : Join lists contained as elements in the Series/Index.
 |
 |      Examples
 |      --------
 |      When not passing `others`, all values are concatenated into a single
 |      string:
 |
 |      >>> s = pd.Series(['a', 'b', np.nan, 'd'])
 |      >>> s.str.cat(sep=' ')
 |      'a b d'
 |
 |      By default, NA values in the Series are ignored. Using `na_rep`, they
 |      can be given a representation:
 |
 |      >>> s.str.cat(sep=' ', na_rep='?')
 |      'a b ? d'
 |
 |      If `others` is specified, corresponding values are concatenated with
 |      the separator. Result will be a Series of strings.
 |
 |      >>> s.str.cat(['A', 'B', 'C', 'D'], sep=',')
 |      0    a,A
 |      1    b,B
 |      2    NaN
 |      3    d,D
 |      dtype: object
 |
 |      Missing values will remain missing in the result, but can again be
 |      represented using `na_rep`
 |
 |      >>> s.str.cat(['A', 'B', 'C', 'D'], sep=',', na_rep='-')
 |      0    a,A
 |      1    b,B
 |      2    -,C
 |      3    d,D
 |      dtype: object
 |
 |      If `sep` is not specified, the values are concatenated without
 |      separation.
 |
 |      >>> s.str.cat(['A', 'B', 'C', 'D'], na_rep='-')
 |      0    aA
 |      1    bB
 |      2    -C
 |      3    dD
 |      dtype: object
 |
 |      Series with different indexes can be aligned before concatenation. The
 |      `join`-keyword works as in other methods.
 |
 |      >>> t = pd.Series(['d', 'a', 'e', 'c'], index=[3, 0, 4, 2])
 |      >>> s.str.cat(t, join='left', na_rep='-')
 |      0    aa
 |      1    b-
 |      2    -c
 |      3    dd
 |      dtype: object
 |      >>>
 |      >>> s.str.cat(t, join='outer', na_rep='-')
 |      0    aa
 |      1    b-
 |      2    -c
 |      3    dd
 |      4    -e
 |      dtype: object
 |      >>>
 |      >>> s.str.cat(t, join='inner', na_rep='-')
 |      0    aa
 |      2    -c
 |      3    dd
 |      dtype: object
 |      >>>
 |      >>> s.str.cat(t, join='right', na_rep='-')
 |      3    dd
 |      0    aa
 |      4    -e
 |      2    -c
 |      dtype: object
 |
 |      For more examples, see :ref:`here <text.concatenate>`.
 |
 |  center(self, width, fillchar: 'str' = ' ')
 |      Pad left and right side of strings in the Series/Index.
 |
 |      Equivalent to :meth:`str.center`.
 |
 |      Parameters
 |      ----------
 |      width : int
 |          Minimum width of resulting string; additional characters will be filled
 |          with ``fillchar``.
 |      fillchar : str
 |          Additional character for filling, default is whitespace.
 |
 |      Returns
 |      -------
 |      Series/Index of objects.
 |
 |  contains(self, pat, case: 'bool' = True, flags: 'int' = 0, na=None, regex: 'bool' = True)
 |      Test if pattern or regex is contained within a string of a Series or Index.
 |
 |      Return boolean Series or Index based on whether a given pattern or regex is
 |      contained within a string of a Series or Index.
 |
 |      Parameters
 |      ----------
 |      pat : str
 |          Character sequence or regular expression.
 |      case : bool, default True
 |          If True, case sensitive.
 |      flags : int, default 0 (no flags)
 |          Flags to pass through to the re module, e.g. re.IGNORECASE.
 |      na : scalar, optional
 |          Fill value for missing values. The default depends on dtype of the
 |          array. For object-dtype, ``numpy.nan`` is used. For ``StringDtype``,
 |          ``pandas.NA`` is used.
 |      regex : bool, default True
 |          If True, assumes the pat is a regular expression.
 |
 |          If False, treats the pat as a literal string.
 |
 |      Returns
 |      -------
 |      Series or Index of boolean values
 |          A Series or Index of boolean values indicating whether the
 |          given pattern is contained within the string of each element
 |          of the Series or Index.
 |
 |      See Also
 |      --------
 |      match : Analogous, but stricter, relying on re.match instead of re.search.
 |      Series.str.startswith : Test if the start of each string element matches a
 |          pattern.
 |      Series.str.endswith : Same as startswith, but tests the end of string.
 |
 |      Examples
 |      --------
 |      Returning a Series of booleans using only a literal pattern.
 |
 |      >>> s1 = pd.Series(['Mouse', 'dog', 'house and parrot', '23', np.NaN])
 |      >>> s1.str.contains('og', regex=False)
 |      0    False
 |      1     True
 |      2    False
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Returning an Index of booleans using only a literal pattern.
 |
 |      >>> ind = pd.Index(['Mouse', 'dog', 'house and parrot', '23.0', np.NaN])
 |      >>> ind.str.contains('23', regex=False)
 |      Index([False, False, False, True, nan], dtype='object')
 |
 |      Specifying case sensitivity using `case`.
 |
 |      >>> s1.str.contains('oG', case=True, regex=True)
 |      0    False
 |      1    False
 |      2    False
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Specifying `na` to be `False` instead of `NaN` replaces NaN values
 |      with `False`. If Series or Index does not contain NaN values
 |      the resultant dtype will be `bool`, otherwise, an `object` dtype.
 |
 |      >>> s1.str.contains('og', na=False, regex=True)
 |      0    False
 |      1     True
 |      2    False
 |      3    False
 |      4    False
 |      dtype: bool
 |
 |      Returning 'house' or 'dog' when either expression occurs in a string.
 |
 |      >>> s1.str.contains('house|dog', regex=True)
 |      0    False
 |      1     True
 |      2     True
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Ignoring case sensitivity using `flags` with regex.
 |
 |      >>> import re
 |      >>> s1.str.contains('PARROT', flags=re.IGNORECASE, regex=True)
 |      0    False
 |      1    False
 |      2     True
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Returning any digit using regular expression.
 |
 |      >>> s1.str.contains('\\d', regex=True)
 |      0    False
 |      1    False
 |      2    False
 |      3     True
 |      4      NaN
 |      dtype: object
 |
 |      Ensure `pat` is a not a literal pattern when `regex` is set to True.
 |      Note in the following example one might expect only `s2[1]` and `s2[3]` to
 |      return `True`. However, '.0' as a regex matches any character
 |      followed by a 0.
 |
 |      >>> s2 = pd.Series(['40', '40.0', '41', '41.0', '35'])
 |      >>> s2.str.contains('.0', regex=True)
 |      0     True
 |      1     True
 |      2    False
 |      3     True
 |      4    False
 |      dtype: bool
 |
 |  count(self, pat, flags: 'int' = 0)
 |      Count occurrences of pattern in each string of the Series/Index.
 |
 |      This function is used to count the number of times a particular regex
 |      pattern is repeated in each of the string elements of the
 |      :class:`~pandas.Series`.
 |
 |      Parameters
 |      ----------
 |      pat : str
 |          Valid regular expression.
 |      flags : int, default 0, meaning no flags
 |          Flags for the `re` module. For a complete list, `see here
 |          <https://docs.python.org/3/howto/regex.html#compilation-flags>`_.
 |      **kwargs
 |          For compatibility with other string methods. Not used.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Same type as the calling object containing the integer counts.
 |
 |      See Also
 |      --------
 |      re : Standard library module for regular expressions.
 |      str.count : Standard library version, without regular expression support.
 |
 |      Notes
 |      -----
 |      Some characters need to be escaped when passing in `pat`.
 |      eg. ``'$'`` has a special meaning in regex and must be escaped when
 |      finding this literal character.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['A', 'B', 'Aaba', 'Baca', np.nan, 'CABA', 'cat'])
 |      >>> s.str.count('a')
 |      0    0.0
 |      1    0.0
 |      2    2.0
 |      3    2.0
 |      4    NaN
 |      5    0.0
 |      6    1.0
 |      dtype: float64
 |
 |      Escape ``'$'`` to find the literal dollar sign.
 |
 |      >>> s = pd.Series(['$', 'B', 'Aab$', '$$ca', 'C$B$', 'cat'])
 |      >>> s.str.count('\\$')
 |      0    1
 |      1    0
 |      2    1
 |      3    2
 |      4    2
 |      5    0
 |      dtype: int64
 |
 |      This is also available on Index
 |
 |      >>> pd.Index(['A', 'A', 'Aaba', 'cat']).str.count('a')
 |      Index([0, 0, 2, 1], dtype='int64')
 |
 |  decode(self, encoding, errors: 'str' = 'strict')
 |      Decode character string in the Series/Index using indicated encoding.
 |
 |      Equivalent to :meth:`str.decode` in python2 and :meth:`bytes.decode` in
 |      python3.
 |
 |      Parameters
 |      ----------
 |      encoding : str
 |      errors : str, optional
 |
 |      Returns
 |      -------
 |      Series or Index
 |
 |  encode(self, encoding, errors: 'str' = 'strict')
 |      Encode character string in the Series/Index using indicated encoding.
 |
 |      Equivalent to :meth:`str.encode`.
 |
 |      Parameters
 |      ----------
 |      encoding : str
 |      errors : str, optional
 |
 |      Returns
 |      -------
 |      Series/Index of objects
 |
 |  endswith(self, pat: 'str | tuple[str, ...]', na: 'Scalar | None' = None) -> 'Series | Index'
 |      Test if the end of each string element matches a pattern.
 |
 |      Equivalent to :meth:`str.endswith`.
 |
 |      Parameters
 |      ----------
 |      pat : str or tuple[str, ...]
 |          Character sequence or tuple of strings. Regular expressions are not
 |          accepted.
 |      na : object, default NaN
 |          Object shown if element tested is not a string. The default depends
 |          on dtype of the array. For object-dtype, ``numpy.nan`` is used.
 |          For ``StringDtype``, ``pandas.NA`` is used.
 |
 |      Returns
 |      -------
 |      Series or Index of bool
 |          A Series of booleans indicating whether the given pattern matches
 |          the end of each string element.
 |
 |      See Also
 |      --------
 |      str.endswith : Python standard library string method.
 |      Series.str.startswith : Same as endswith, but tests the start of string.
 |      Series.str.contains : Tests if string element contains a pattern.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['bat', 'bear', 'caT', np.nan])
 |      >>> s
 |      0     bat
 |      1    bear
 |      2     caT
 |      3     NaN
 |      dtype: object
 |
 |      >>> s.str.endswith('t')
 |      0     True
 |      1    False
 |      2    False
 |      3      NaN
 |      dtype: object
 |
 |      >>> s.str.endswith(('t', 'T'))
 |      0     True
 |      1    False
 |      2     True
 |      3      NaN
 |      dtype: object
 |
 |      Specifying `na` to be `False` instead of `NaN`.
 |
 |      >>> s.str.endswith('t', na=False)
 |      0     True
 |      1    False
 |      2    False
 |      3    False
 |      dtype: bool
 |
 |  extract(self, pat: 'str', flags: 'int' = 0, expand: 'bool' = True) -> 'DataFrame | Series | Index'
 |      Extract capture groups in the regex `pat` as columns in a DataFrame.
 |
 |      For each subject string in the Series, extract groups from the
 |      first match of regular expression `pat`.
 |
 |      Parameters
 |      ----------
 |      pat : str
 |          Regular expression pattern with capturing groups.
 |      flags : int, default 0 (no flags)
 |          Flags from the ``re`` module, e.g. ``re.IGNORECASE``, that
 |          modify regular expression matching for things like case,
 |          spaces, etc. For more details, see :mod:`re`.
 |      expand : bool, default True
 |          If True, return DataFrame with one column per capture group.
 |          If False, return a Series/Index if there is one capture group
 |          or DataFrame if there are multiple capture groups.
 |
 |      Returns
 |      -------
 |      DataFrame or Series or Index
 |          A DataFrame with one row for each subject string, and one
 |          column for each group. Any capture group names in regular
 |          expression pat will be used for column names; otherwise
 |          capture group numbers will be used. The dtype of each result
 |          column is always object, even when no match is found. If
 |          ``expand=False`` and pat has only one capture group, then
 |          return a Series (if subject is a Series) or Index (if subject
 |          is an Index).
 |
 |      See Also
 |      --------

In [40]:
filtro2=s2.str.contains("m")
filtro2

0    False
1    False
2     True
3     True
dtype: bool

In [41]:
s2[filtro2]

2      melon
3    manzana
dtype: object

In [42]:
numeros=pd.Series([10,20,30,40,50])
numeros

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [43]:
promedio=numeros.mean()
print(f"el promedio es : {promedio}")

el promedio es : 30.0

In [45]:
m=numeros.max()
m

50

In [46]:
mi= numeros.min()
mi

10

In [47]:
total = numeros.sum()
total

150

In [48]:
desviacion = numeros.std()
desviacion

15.811388300841896

In [51]:
medallas = pd.read_csv("/content/medallas.csv")
medallas.head(2)

   Oro  Plata  Bronce  Total       Pais
0  NaN    1.0     2.0      3  Argentina
1  NaN    2.0     2.0      4    Armenia

In [52]:
medallas.head()

    Oro  Plata  Bronce  Total        Pais
0   NaN    1.0     2.0      3   Argentina
1   NaN    2.0     2.0      4     Armenia
2  17.0    7.0    22.0     46   Australia
3   1.0    1.0     5.0      7     Austria
4   NaN    3.0     4.0      7  Azerbaijan

In [53]:
medallas.shape

(93, 5)

In [54]:
medallas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [55]:
medallas.isnull().sum()

Oro       28
Plata     24
Bronce    17
Total      0
Pais       0
dtype: int64

In [56]:
medallas.describe()

             Oro      Plata     Bronce       Total
count  65.000000  69.000000  76.000000   93.000000
mean    4.400000   4.768116   4.934211   10.548387
std     7.633806   7.276362   6.261705   18.897617
min     1.000000   1.000000   1.000000    1.000000
25%     1.000000   1.000000   1.000000    2.000000
50%     2.000000   2.000000   2.000000    4.000000
75%     3.000000   5.000000   5.250000    8.000000
max    39.000000  41.000000  33.000000  113.000000

In [57]:
medallas.fillna(0,inplace=True)
medallas

     Oro  Plata  Bronce  Total          Pais
0    0.0    1.0     2.0      3     Argentina
1    0.0    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    0.0    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   0.0    1.0     0.0      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    0.0     2.0      5    Uzbekistan
92   1.0    3.0     0.0      4     Venezuela

[93 rows x 5 columns]

In [58]:
medallas["Oro"]=medallas["Oro"].astype(int)
medallas["Plata"]=medallas["Plata"].astype(int)
medallas["Bronce"]=medallas["Bronce"].astype(int)
medallas

    Oro  Plata  Bronce  Total          Pais
0     0      1       2      3     Argentina
1     0      2       2      4       Armenia
2    17      7      22     46     Australia
3     1      1       5      7       Austria
4     0      3       4      7    Azerbaijan
..  ...    ...     ...    ...           ...
88    0      1       0      1  Turkmenistan
89    2      1       1      4        Uganda
90    1      6      12     19       Ukraine
91    3      0       2      5    Uzbekistan
92    1      3       0      4     Venezuela

[93 rows x 5 columns]

In [65]:
top_3_oro=medallas.sort_values("Oro", ascending=False)
medallas.head(3)

   Oro  Plata  Bronce  Total       Pais
0    0      1       2      3  Argentina
1    0      2       2      4    Armenia
2   17      7      22     46  Australia

In [66]:
t=medallas["Total"] >10
mas_10_medallas=medallas[t]
mas_10_medallas.sort_values("Total", ascending=False)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
2    17      7      22     46                   Australia
32    1     11      16     37                     Germany
60    1     12      14     36                 Netherlands
30    1     12      11     33                      France
14    7      6      11     24                      Canada
11    7      6       8     21                      Brazil
90    1      6      12     19                     Ukraine
81    3      8       6     17                       Spain
19    7      3       5     15                        Cuba
66    4      5       5     14                      Poland
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
15    2      4       6     12              Chinese Taipei
21    3      4       4     11                     Denmark
20    4      4       3     11              Czech Republic